# Prior to conda-forge, Copyright 2018-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "epoxy" %}
{% set version = "1.5.10" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/libepoxy/{{ version_majmin }}/libepoxy-{{ version }}.tar.xz
  sha256: 072cda4b59dd098bba8c2363a6247299db1fa89411dc221c8b81b8ee8192e623

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('epoxy', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    # The following CDTs are needed for building against egl/gl.
    # We only actually need the headers, as epoxy doesn't link to the gl libs.
    # We can ignore pkg-config saying it can't find egl/gl (due to missing deps
    # included in the .pc files) since this is only currently used to add
    # egl/gl as Requires.private dependencies in the epoxy.pc file, which
    # itself is only used to propagate build flags from the GL libs to epoxy,
    # and there is nothing interesting to propagate from mesa. If needed, this
    # should get pkg-config to find egl/gl (check their .pc files to verify,
    # probably only needed for mesa < 19):
    #   build:
    #     - {{ cdt('libxxf86vm-devel') }}   # [linux]
    #   host:
    #     - libdrm                 # [linux]
    #     - xorg-libxdamage        # [linux]
    #     - xorg-libxext           # [linux]
    #     - xorg-libxfixes         # [linux]
    #     - xorg-xf86vidmodeproto  # [linux]
    # Since these dependencies would be needed wherever epoxy.pc is consumed,
    # it is simpler to leave them off for now while we can.
    - {{ cdt('mesa-libegl-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - meson
    - ninja
    - pkg-config
  host:
    - xorg-libx11  # [linux]

test:
  commands:
    - test -f $PREFIX/include/epoxy/common.h         # [unix]
    - test -f $PREFIX/include/epoxy/egl.h            # [linux]
    - test -f $PREFIX/include/epoxy/egl_generated.h  # [linux]
    - test -f $PREFIX/include/epoxy/gl.h             # [unix]
    - test -f $PREFIX/include/epoxy/gl_generated.h   # [unix]
    - test -f $PREFIX/include/epoxy/glx.h            # [linux]
    - test -f $PREFIX/include/epoxy/glx_generated.h  # [linux]
    - test -f $PREFIX/lib/libepoxy${SHLIB_EXT}       # [unix]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\common.h exit 1         # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\gl.h exit 1             # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\gl_generated.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\wgl.h exit 1            # [win]
    - if not exist %PREFIX%\\Library\\include\\epoxy\\wgl_generated.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\epoxy-0.dll exit 1                 # [win]
    - if not exist %PREFIX%\\Library\\lib\\epoxy.lib exit 1                   # [win]

about:
  home: https://github.com/anholt/libepoxy
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A library for handling OpenGL function pointer management for you.
  description: |
    Epoxy is a library for handling OpenGL function pointer management for you.

    It hides the complexity of dlopen(), dlsym(), glXGetProcAddress(),
    eglGetProcAddress(), etc. from the app developer, with very little
    knowledge needed on their part. They get to read GL specs and write code
    using undecorated function names like glCompileShader().

    Don't forget to check for your extensions or versions being present before
    you use them, just like before! We'll tell you what you forgot to check
    for instead of just segfaulting, though.
  dev_url: https://github.com/anholt/libepoxy

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
